### ISSUE TITLE
[Request] New items in food section

### ISSUE THREAD

**Issue by Fridan99** [kristkos/KCTG-5e#1]
I would like to make a suggestion. 
Maybe in the food section you could implement eatable mushrooms, seeds, and meat or fish items. :P

Is only a suggestion!

Nice module :)

**Comment by kristkos** [comment]
Hello there, 

Expansions for most of the items you said are planned already, however, time is very limited due to the job.  You can check our discord as I made a rundown of future packs, as a channel was made dedicated for this in particular.
Thank you so much for the comment👍
